### ISSUE TITLE
Configure not recognising 'legend_kwargs'

### ISSUE THREAD

**Issue by jacobseiler** [Samreay/ChainConsumer#38]
Hey Sam,  just started using this spiffing package today after hearing about how awesome it is from Caitlin for ages.

I'm trying to plot multiple contours with different colours.  However for some reason ``legend_kwargs`` is not recognised.  I've tried copy pasting the code directly from the Documents but it's still generating the error.

```
# G1 and G2 are arrays of galaxy  information.

c = ChainConsumer()
x_label = "$\mathrm{M}_\mathrm{H} \: [\mathrm{M}_\odot h^{-1}]$"
y_label = "$\mathrm{M}_* \: [\mathrm{M}_\odot h^{-1}]$"

w1 = np.where((G1.Mvir > 0.0) & (G1.StellarMass > 0.1))[0]
w2 = np.where((G2.Mvir > 0.0) & (G2.StellarMass > 0.1))[0]
halomass1 = np.log10(G1.Mvir[w1] * 1.0e10 / self.Hubble_h)
stellarmass1 = np.log10(G1.StellarMass[w1] * 1.0e10 / self.Hubble_h)
 
halomass2 = np.log10(G2.Mvir[w2] * 1.0e10 / self.Hubble_h)
stellarmass2 = np.log10(G2.StellarMass[w2] * 1.0e10 / self.Hubble_h)

c.add_chain([halomass1, stellarmass1], parameters=[x_label, y_label], name = "$\eta_\mathrm{SN} = 5 \: \mathrm{x} \: 10^{-3}$")
c.add_chain([halomass2, stellarmass2], parameters=[x_label, y_label], name = "$\eta_\mathrm{SN} = 5 \: \mathrm{x} \: 10^{-4}$")

c.configure(linestyles=["-", "--"], sigmas=[0, 1, 2, 3],
legend_kwargs={"loc": "upper left", "fontsize": 10},
legend_color_text=False, legend_location=(0, 0))

fig = c.plotter.plot(filename = OutputDir + 'XX.StellarMass_HaloMass' + OutputFormat, figsize = 1.0)
```
Yields
```
Traceback (most recent call last):
  File "allresults.py", line 1443, in <module>
    res.StellarMass_HaloMass(G1, G2, G4)
  File "allresults.py", line 1320, in StellarMass_HaloMass
    legend_color_text=False, legend_location=(0, 0))
TypeError: configure() got an unexpected keyword argument 'legend_kwargs'
```
I'm also getting the error for ``legend_color_text`` and ``legend_artists`` (haven't tried any other esoteric options). 

Thanks!

**Comment by Samreay** [comment]
I assume you need to update chainconsumer, those are relatively new options

**Comment by jacobseiler** [comment]
Mmm I must have installed a very old version a long time ago and my ``pip install`` a few hours ago didn't actually do anything.

Cheers.
