### ISSUE TITLE
from scipy.stats.stats import ss deprecated

### ISSUE THREAD

**Issue by jpratmarti** [Samreay/ChainConsumer#56]
Hi, 

I cannot import chainconsumer because it gives me this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Judit/anaconda/lib/python2.7/site-packages/chainconsumer/__init__.py", line 5, in <module>
    from .chainconsumer import ChainConsumer
  File "/Users/Judit/anaconda/lib/python2.7/site-packages/chainconsumer/chainconsumer.py", line 6, in <module>
    from .diagnostic import Diagnostic
  File "/Users/Judit/anaconda/lib/python2.7/site-packages/chainconsumer/diagnostic.py", line 4, in <module>
    from statsmodels.regression.linear_model import yule_walker
  File "/Users/Judit/anaconda/lib/python2.7/site-packages/statsmodels/regression/__init__.py", line 1, in <module>
    from linear_model import yule_walker
  File "/Users/Judit/anaconda/lib/python2.7/site-packages/statsmodels/regression/linear_model.py", line 36, in <module>
    from scipy.stats.stats import ss
ImportError: cannot import name ss
```

I have version 1.0.0 of scipy, and according to https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.stats.ss.html, it says ss is deprecated. Does this happen to other people too? How can I fix this? 

Thanks!

Judit

**Comment by Samreay** [comment]
Hi Judit,

Looking at the stack trace, it appears the issue is not with ChainConsumer, but with statsmodels.

Have you tried updating statsmodels via `pip install -U statsmodels` or `conda update statsmodels`? If not, can you let me know if that fixes the issue?

**Comment by jpratmarti** [comment]
Great, it worked! I thought the issue was with scipy... 
Thanks a lot!

Judit

**Comment by Samreay** [comment]
Glad it was a simple fix!
