### ISSUE TITLE
Legend error

### ISSUE THREAD

**Issue by jpratmarti** [Samreay/ChainConsumer#57]
Hi again,

I'm having problems to put a legend in a plot. For instance when I run this simple example code,

```
import numpy as np
from chainconsumer import ChainConsumer
data = np.random.multivariate_normal([0, 1], np.eye(2), size=100000)
data2 = np.random.multivariate_normal([0, 2], np.eye(2), size=100000)
c = ChainConsumer()
c.add_chain(data, name = 'Data')
c.add_chain(data2, name = 'Data2')
fig = c.plotter.plot()
fig.set_size_inches(4.5 + fig.get_size_inches())
fig.savefig('test_chainconsumer.pdf')
```

I get this error:

```
Traceback (most recent call last):
  File "test_chainconsumer.py", line 8, in <module>
    fig = c.plotter.plot()
  File "/Users/Judit/anaconda/lib/python2.7/site-packages/chainconsumer/plotter.py", line 198, in plot
    leg = ax.legend(artists, names, **legend_kwargs)
  File "/Users/Judit/anaconda/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 513, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'markerfirst'
```
That I only get when there is a legend to plot. If I set legend=False, the error goes away. How can I fix that? 

Thanks!

Judit

**Comment by Samreay** [comment]
What version of matplotlib do you have?

Try running `pip install matplotlib==2.1.0` to get the latest (but non-bugged) version of matplotlib and let me know if that does anything.

**Comment by jpratmarti** [comment]
Great, worked again! I had an older version of matplotlib. 

Thanks,

Judit

**Comment by Samreay** [comment]
Glad I could help!
