### ISSUE TITLE
Weights as integer

### ISSUE THREAD

**Issue by dparkins** [Samreay/ChainConsumer#77]
I get an error when I pass an array of integers for the MCMC weights (genereted by Metropolis-Hastings). Jesus and Antony's new cosmology analysis code cobaya (https://cobaya.readthedocs.io/en/latest/) stores the MCMC weights in the output file as integer rather than float. Is there any way ChainConsumer can detect the type of the weights, and convert them if necessary?

**Comment by Samreay** [comment]
Hey David, the code *shouldn't* care about whether its an int or a float, can you throw me the full error so I can see where I've done something silly?

**Comment by dparkins** [comment]
```
UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
```
and

```
Traceback (most recent call last):
  File "/Users/willdavison/Documents/Project/Planck/cobaya_analysis.py", line 27, in <module>
    c.plotter.plot()#parameters=[r'$\Omega_{m}$', r'$\Omega_{DE}$'])#filename="/Users/willdavison/Documents/Project/Planck/cobaya_test.png")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/chainconsumer/plotter.py", line 166, in plot
    m = self._plot_bars(ax, p1, chain, flip=do_flip, summary=param_summary)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/chainconsumer/plotter.py", line 1204, in _plot_bars
    fit_values = self.parent.analysis.get_parameter_summary(chain, parameter)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/chainconsumer/analysis.py", line 214, in get_parameter_summary
    return chain.get_summary(parameter, callback)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/chainconsumer/chain.py", line 165, in get_summary
    result = callback(self, param)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/chainconsumer/analysis.py", line 483, in get_parameter_summary_max
    i1 = startIndex - np.where(ys[:startIndex][::-1] < mid)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by Samreay** [comment]
Ah this one is going to be fun to debug. Is there any chance you can email me or send me the chain itself and your code? If I can play around itll be far easier, because this doesn't scream integer to me, seems like something else is afoot!

**Comment by dparkins** [comment]
This was a problem my student found, but when I try to replicate it, I cannot replicate it myself on my machine.

**Comment by dparkins** [comment]
This is my script:

**Comment by Samreay** [comment]
Hmm interesting, nothing in that code should cause an issue. Are you able to have your student update astropy, numpy and chainconsumer and let me know if they still have issues?

**Comment by dparkins** [comment]
OK, I will do that.
